## Best Deal 

Clone the project:

```
git clone git@github.com:uriklar/BestDealApi.git
```

#### To test the extension

1. Open you chrome browser
2. In the address line type: chrome://extensions/
3. Make sure the checkbox titled "Developer Mode" is checked
5. Click on "Load unpacked extension..."
6. Select the folder "BDChromeExtensionExternal" and click "Select"

Once you have done this you will be able to test the extension on these three providers:
Booking.com, Hotels.com and Trip Advisor


### To setup the dev environment

**Note**: these steps require you have Git and a working Rails environment setup.

1. cd into directory created when cloning the app
2. run the following command to setup and populate the database:

```rake db:setup```

3. start the server by running:

```rails s```


You will also need to change two lines in the code to develop locally:
1. In app/public/main.js:

```javascript
function API(viewSrvc) {
	// prod_url = https://blooming-cliffs-1855.herokuapp.com
	// dev_url = http://localhost:3000
	this.url = "https://blooming-cliffs-1855.herokuapp.com",
	this.viewSrvc = viewSrvc
}
```


Change the line this.url to equal the dev_url

2. In BDChromeExtensionExternal/main.js
```javascript
// prod_url = https://blooming-cliffs-1855.herokuapp.com
// dev_url = http://localhost:3000
(function() {
	var url = 'https://blooming-cliffs-1855.herokuapp.com'
	$('head').append("<script type='text/javascript' src='"+url+"/main.js'>");
	$('head').append("<link rel='stylesheet' type='text/css' href='"+url+"/main.css'>");
})();
```

Change the line var url to equal the dev_url

**Note**: After making changes to BDChromeExtensionExternal/main.js you will need to:

1. go to chrome://extensions/
2. find the extension "bestdeal-dev-with-external"
3. click "Reload"
